# =====  docker-compose.yml  =====
# Для Docker Desktop на Windows/Mac, только архитектура linux/amd64

networks:
  bot_net:
    driver: bridge

services:
  # --- FREQTRADE (core bot) ------------------------------------
  freqtrade:
    image: ghcr.io/tyrannya/ProjectChimera:latest
    platform: linux/amd64
    container_name: freqtrade
    env_file:
      - .env
    networks:
      - bot_net
    volumes:
      - ./conf:/freqtrade/conf:ro
      - ./strategies:/freqtrade/user_data/strategies:ro
      - ./tools:/freqtrade/user_data/tools:ro
    command: sleep infinity

  # --- NN INFER (BentoML-сервис с нейросетью) -------------------
  nn_infer:
    image: ghcr.io/tyrannya/nn_infer:latest
    platform: linux/amd64
    container_name: nn_infer
    networks:
      - bot_net
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/livez"]
      interval: 30s
      timeout: 5s
      retries: 3

  # --- PROMETHEUS ----------------------------------------------
  prometheus:
    image: prom/prometheus:latest
    platform: linux/amd64
    container_name: prometheus
    networks:
      - bot_net
    ports:
      - "9090:9090"
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  # --- GRAFANA --------------------------------------------------
  grafana:
    image: grafana/grafana:latest
    platform: linux/amd64
    container_name: grafana
    networks:
      - bot_net
    ports:
      - "3001:3000"
