"""The committed P2b and P2c evidence, checked rather than described.

Three kinds of claim live here, and they are checked three different ways
because they are three different kinds of thing.

**Primary evidence is pinned by its bytes.** A cell's metrics and its per-sample
predictions cannot be rebuilt without re-fitting, so a byte change in one is a
change in the research result. Every checksum manifest in the repository is
re-hashed here, with no exemptions of any kind, through the same
:func:`tools.freeze_evidence.check` that ``--verify`` calls — so "frozen" has
exactly one meaning whether a person or CI is asking.

**Derived evidence is pinned by what it says.** A comparison is regenerated from
the cells whenever the aggregator improves, and it is supposed to: widening a
recomputation from ten trading keys to twenty-three rewrites the file without
touching a number the research reported. Hashing it alongside primary evidence
produced three manifests that failed their own verification and a test that
excused the failures by matching ``_comparison/`` in the path. So the fold
counts, the verdicts and the integrity counters are asserted directly instead,
and a regenerated report that changed a finding fails while one that only
improved its own prose does not.

**The freeze tool itself is pinned by adversarial use.** A verifier that only
ever sees good input proves nothing — a function returning zero problems would
pass. Every rejection it claims is exercised against a sandboxed tree.

Nothing here needs a dataset, a fit or a network. It all reads committed files.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from nn.information_sets import CHECKPOINTS, ablation_set_names
from nn.simple_models import SIMPLE_MODEL_NAMES
from tools import freeze_evidence
from tools.freeze_evidence import DERIVED, EVIDENCE_CLASS_KEY, PRIMARY

ROOT = Path(__file__).resolve().parent.parent
BENCHMARK = ROOT / "artifacts" / "benchmark"

#: Every checksum manifest this repository stands behind, discovered rather than
#: listed. A checkpoint that freezes new evidence is covered the moment its
#: manifest lands, instead of when someone remembers to add a name here — and
#: `test_the_repository_has_the_manifests_these_tests_think_it_has` names the
#: expected set once, so a manifest that vanished cannot take its own
#: verification quietly with it.
MANIFESTS = tuple(sorted(path.name for path in (ROOT / "artifacts").glob("*_SHA256SUMS.txt")))

#: The comparison directories this branch regenerates. Derived by
#: declaration, and asserted to be so below rather than assumed.
DERIVED_DIRS = (
    BENCHMARK / "btc_p2b_comparison",
    BENCHMARK / "btc_p2c_comparison",
    BENCHMARK / "btc_p2b_ablation_xgboost",
    BENCHMARK / "btc_p2b_regimes",
    BENCHMARK / "btc_p3_comparison",
    BENCHMARK / "btc_p4_comparison",
    BENCHMARK / "btc_p5_comparison",
)


# --------------------------------------------------------------------------- #
# A. primary evidence is pinned by its bytes
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("manifest", MANIFESTS)
def test_every_frozen_file_still_hashes_to_its_manifest(manifest):
    """No exemptions. Not by directory, not by suffix, not by evidence class.

    The previous version of this test allowed any covered path containing
    ``_comparison/`` to fail its hash, which made three manifests permanently
    and deliberately wrong. A checksum that means "frozen unless it is not"
    trains a reader to ignore the one signal it exists to send.
    """
    path = ROOT / "artifacts" / manifest
    assert path.is_file(), f"{manifest} is missing"
    entries = freeze_evidence.manifest_entries(path)
    assert entries, f"{manifest} is empty"
    assert freeze_evidence.check(path) == []


@pytest.mark.parametrize("manifest", MANIFESTS)
def test_no_manifest_covers_derived_evidence(manifest):
    """The rule that keeps the test above from ever needing an exemption again."""
    for _, name in freeze_evidence.manifest_entries(ROOT / "artifacts" / manifest):
        directory = (ROOT / name).parent
        assert freeze_evidence.evidence_class_of(directory) != DERIVED, (
            f"{manifest} freezes {name}, which its own directory declares derived. "
            "A derived file is regenerated by design; hashing it guarantees a "
            "manifest that fails for a reason nobody should act on."
        )


def test_the_regenerated_reports_declare_themselves_derived():
    """The other half: the exclusion must be a declaration, not a path pattern."""
    for directory in DERIVED_DIRS:
        assert directory.is_dir(), f"{directory} is missing"
        assert freeze_evidence.evidence_class_of(directory) == DERIVED


def test_every_frozen_directory_would_be_accepted_by_the_freeze_tool():
    """Nothing a manifest covers would be excluded if it were frozen again.

    The committed cells declare no evidence class: they were written before the
    field existed, and `evidence_class_of` returns `None` for them. That is the
    intended default rather than a gap — a new aggregator has to opt *into*
    being excluded, so an undeclared directory is frozen as primary and only an
    explicit `derived` is refused. What must never happen is a covered
    directory that would now be refused, which is what this asserts.
    """
    covered = {
        (ROOT / name).parent
        for manifest in MANIFESTS
        for _, name in freeze_evidence.manifest_entries(ROOT / "artifacts" / manifest)
    }
    assert covered, "the manifests cover nothing"
    for directory in covered:
        assert freeze_evidence.evidence_class_of(directory) != DERIVED


# --------------------------------------------------------------------------- #
# B. the freeze tool, used adversarially
#
# `ROOT` is redirected at a sandbox so these can mutate and delete files. The
# committed evidence is never written to.
# --------------------------------------------------------------------------- #
@pytest.fixture
def sandbox(tmp_path, monkeypatch):
    """A repository-shaped tree with one primary cell and one derived report."""
    monkeypatch.setattr(freeze_evidence, "ROOT", tmp_path)
    cell = tmp_path / "artifacts" / "benchmark" / "demo_cell"
    cell.mkdir(parents=True)
    (cell / "p2b.json").write_text(json.dumps({EVIDENCE_CLASS_KEY: PRIMARY, "fold": 0}))
    (cell / "outer_predictions.parquet").write_bytes(b"not really a parquet")
    (cell / "STATUS.md").write_text("# CURRENT\n")

    report = tmp_path / "artifacts" / "benchmark" / "demo_comparison"
    report.mkdir(parents=True)
    (report / "p2b_comparison.json").write_text(json.dumps({EVIDENCE_CLASS_KEY: DERIVED}))
    (report / "p2b_comparison.md").write_text("# derived\n")
    return tmp_path


def _freeze(sandbox, *directories) -> Path:
    out = sandbox / "artifacts" / "DEMO_SHA256SUMS.txt"
    assert freeze_evidence.freeze([Path(d) for d in directories], out) == 0
    return out


def test_freezing_a_primary_cell_covers_every_evidence_file_in_it(sandbox):
    manifest = _freeze(sandbox, sandbox / "artifacts" / "benchmark" / "demo_cell")
    covered = {name for _, name in freeze_evidence.manifest_entries(manifest)}
    assert covered == {
        "artifacts/benchmark/demo_cell/p2b.json",
        "artifacts/benchmark/demo_cell/outer_predictions.parquet",
        "artifacts/benchmark/demo_cell/STATUS.md",
    }
    assert freeze_evidence.check(manifest) == []


def test_freezing_refuses_a_directory_that_declares_itself_derived(sandbox):
    with pytest.raises(SystemExit, match="refusing to freeze derived evidence"):
        _freeze(sandbox, sandbox / "artifacts" / "benchmark" / "demo_comparison")


def test_freezing_a_glob_that_caught_a_report_refuses_rather_than_dropping_it(sandbox):
    """The realistic mistake: `--out ... artifacts/benchmark/btc_p2b_*`.

    Silently freezing the cells and skipping the report would produce a manifest
    that looks complete and is not, which is worse than a refusal naming the
    directory.
    """
    with pytest.raises(SystemExit, match="demo_comparison"):
        _freeze(
            sandbox,
            sandbox / "artifacts" / "benchmark" / "demo_cell",
            sandbox / "artifacts" / "benchmark" / "demo_comparison",
        )


def test_freezing_refuses_to_overwrite_an_existing_manifest(sandbox):
    _freeze(sandbox, sandbox / "artifacts" / "benchmark" / "demo_cell")
    with pytest.raises(SystemExit, match="already exists"):
        _freeze(sandbox, sandbox / "artifacts" / "benchmark" / "demo_cell")


def test_a_mutated_covered_file_fails_verification(sandbox):
    manifest = _freeze(sandbox, sandbox / "artifacts" / "benchmark" / "demo_cell")
    target = sandbox / "artifacts" / "benchmark" / "demo_cell" / "outer_predictions.parquet"
    target.write_bytes(b"not really a parquet either")
    problems = freeze_evidence.check(manifest)
    assert len(problems) == 1 and problems[0].startswith("CHANGED")
    assert freeze_evidence.verify(manifest) == 1


def test_a_removed_covered_file_fails_verification(sandbox):
    manifest = _freeze(sandbox, sandbox / "artifacts" / "benchmark" / "demo_cell")
    (sandbox / "artifacts" / "benchmark" / "demo_cell" / "STATUS.md").unlink()
    problems = freeze_evidence.check(manifest)
    assert len(problems) == 1 and problems[0].startswith("MISSING")
    assert freeze_evidence.verify(manifest) == 1


def test_a_changed_file_is_not_excused_by_living_in_a_comparison_directory(sandbox):
    """The exact exemption that used to exist, aimed at the exact path shape.

    A directory named `..._comparison` whose artifact declares itself *primary*
    is primary. The name is not the classifier and must not become one again.
    """
    directory = sandbox / "artifacts" / "benchmark" / "misnamed_comparison"
    directory.mkdir(parents=True)
    (directory / "p2b_comparison.json").write_text(json.dumps({EVIDENCE_CLASS_KEY: PRIMARY}))
    manifest = _freeze(sandbox, directory)
    (directory / "p2b_comparison.json").write_text(
        json.dumps({EVIDENCE_CLASS_KEY: PRIMARY, "x": 1})
    )
    problems = freeze_evidence.check(manifest)
    assert len(problems) == 1
    assert "_comparison/" in problems[0]


def test_the_cli_exit_code_and_the_test_suites_check_are_the_same_decision(sandbox):
    manifest = _freeze(sandbox, sandbox / "artifacts" / "benchmark" / "demo_cell")
    assert freeze_evidence.check(manifest) == []
    assert freeze_evidence.verify(manifest) == 0
    (sandbox / "artifacts" / "benchmark" / "demo_cell" / "STATUS.md").write_text("# edited\n")
    assert freeze_evidence.check(manifest) != []
    assert freeze_evidence.verify(manifest) == 1


# --------------------------------------------------------------------------- #
# C. the findings themselves
# --------------------------------------------------------------------------- #
def _comparison(name: str) -> dict:
    return json.loads((BENCHMARK / name / "p2b_comparison.json").read_text())


def test_each_checkpoints_artifacts_identify_as_that_checkpoint():
    """The provenance failure this branch was opened to fix.

    Nine P2c cells and their comparison identified as P2b and stated P2b's
    market-structure question, over chart-structure columns. Every number was
    P2c's; only the identity was wrong, which is why nothing failed.
    """
    for checkpoint, prefix, arms in (
        ("P2b", "btc_p2b", ("ohlcv14", "smc_v1", "ohlcv14_plus_smc_v1")),
        (
            "P2c",
            "btc_p2c",
            ("ohlcv14", "chart_structure_v1", "ohlcv14_plus_chart_structure_v1"),
        ),
        (
            "P3",
            "btc_p3",
            ("ohlcv14", "microstructure_v1", "ohlcv14_plus_microstructure_v1"),
        ),
    ):
        question = CHECKPOINTS[checkpoint].question
        comparison = _comparison(f"{prefix}_comparison")
        assert comparison["checkpoint"] == checkpoint
        assert comparison["question"] == question
        assert comparison["evidence_class"] == DERIVED
        assert (
            (BENCHMARK / f"{prefix}_comparison" / "p2b_comparison.md")
            .read_text()
            .startswith(f"# {checkpoint} —")
        )
        for arm in arms:
            for model in ("logistic_regression", "lightgbm", "xgboost"):
                cell = json.loads(
                    (BENCHMARK / f"{prefix}_{arm}_{model}" / "p2b.json").read_text()
                )
                # Both fields, because either alone can be right while the other
                # is wrong: `load_cell` checks the arm against the columns the
                # cell actually flattened, and the checkpoint against the
                # question it states.
                assert cell["information_set"] == arm
                assert cell["checkpoint"] == checkpoint, f"{prefix}_{arm}_{model}"
                assert cell["question"] == question
                assert cell["evidence_class"] == PRIMARY


def test_the_p2b_question_and_the_p2c_question_are_not_the_same_question():
    assert (
        _comparison("btc_p2b_comparison")["question"]
        != _comparison("btc_p2c_comparison")["question"]
    )
    assert "smc_v1" in _comparison("btc_p2b_comparison")["question"]
    assert "chart_structure_v1" in _comparison("btc_p2c_comparison")["question"]


@pytest.mark.parametrize(
    "name", ["btc_p2b_comparison", "btc_p2c_comparison", "btc_p3_comparison"]
)
def test_every_persisted_row_is_a_planned_row(name):
    """The counters that say the scored sample is the planned sample.

    `snapshot_anchoring` asks whether each persisted row agrees with the
    snapshot at the index it claims. This asks the other question — whether
    those indices are the ones the fold plan selected — and a scorer that
    persisted a consistent but wrong selection passes the first and fails this.
    """
    bound = _comparison(name)["planned_row_alignment"]
    assert bound["cells_checked"] == 9
    assert bound["folds_checked"] == 36
    assert bound["rows_checked"] == 170_451
    assert bound["problems"] == 0
    for counter in (
        "missing_folds",
        "unplanned_folds",
        "non_integer_row_index",
        "duplicate_rows",
        "unsorted_rows",
        "count_mismatches",
        "sample_index_hash_mismatches",
        "first_last_mismatches",
        "cross_fold_rows",
        "snapshot_value_mismatches",
    ):
        assert bound[counter] == 0, counter


def test_both_information_set_checkpoints_reproduce_the_same_frozen_control():
    """P2b, P2c and P3 each re-ran the OHLCV14 control, and it is P2a's.

    All three must equal P2a's frozen seed-42 XGBoost evidence, and therefore
    each other. If adding a feature family ever perturbs the control's sample
    universe, this is what notices.
    """
    p2a = json.loads((BENCHMARK / "btc_p2a_seed_42" / "benchmark.json").read_text())
    frozen = [f["outer_validation"]["xgboost"] for f in p2a["folds"]]
    for checkpoint in (
        "btc_p2b_ohlcv14_xgboost",
        "btc_p2c_ohlcv14_xgboost",
        "btc_p3_ohlcv14_xgboost",
    ):
        cell = json.loads((BENCHMARK / checkpoint / "p2b.json").read_text())
        assert [f["outer_validation"]["xgboost"] for f in cell["folds"]] == frozen


def test_the_p2b_comparison_reports_a_negative_result():
    """The frozen verdicts, pinned so a rerun cannot quietly improve them.

    Not a test of the machinery — a test of the *finding*. P2b answered no, and
    the six fold counts below are what that means. If a later change to the
    comparison moves any of them, the result changed, and that has to be a
    deliberate act with its own evidence rather than a diff nobody read.
    """
    payload = _comparison("btc_p2b_comparison")
    assert payload["sealed_test"] is False
    assert payload["independent_recompute"]["mismatches"] == 0
    assert payload["snapshot_anchoring"]["problems"] == 0

    expected = {
        ("logistic_regression", "smc_v1"): 0,
        ("logistic_regression", "ohlcv14_plus_smc_v1"): 2,
        ("lightgbm", "smc_v1"): 2,
        ("lightgbm", "ohlcv14_plus_smc_v1"): 1,
        ("xgboost", "smc_v1"): 1,
        ("xgboost", "ohlcv14_plus_smc_v1"): 1,
    }
    for (model, arm), folds in expected.items():
        assert payload["deltas"][model][arm]["net_return_improved_folds"] == folds

    # The predeclared bar is three of four. Nothing reached it, which is the
    # finding; asserting it here stops "P2b was positive" from ever being true
    # of this directory without someone changing this line.
    assert all(v < 3 for v in expected.values())


def test_the_p2c_comparison_reports_a_negative_result():
    """P2c's frozen verdicts. Same reasoning as the P2b pin above.

    Every mean delta here is negative, which P2b's was not — there is no arm in
    P2c where pooling the four periods would even have flattered the result.
    """
    payload = _comparison("btc_p2c_comparison")
    assert payload["sealed_test"] is False
    assert payload["independent_recompute"]["mismatches"] == 0
    assert payload["snapshot_anchoring"]["problems"] == 0

    expected = {
        ("logistic_regression", "chart_structure_v1"): 1,
        ("logistic_regression", "ohlcv14_plus_chart_structure_v1"): 0,
        ("lightgbm", "chart_structure_v1"): 1,
        ("lightgbm", "ohlcv14_plus_chart_structure_v1"): 2,
        ("xgboost", "chart_structure_v1"): 1,
        ("xgboost", "ohlcv14_plus_chart_structure_v1"): 1,
    }
    for (model, arm), folds in expected.items():
        entry = payload["deltas"][model][arm]
        assert entry["net_return_improved_folds"] == folds
        assert entry["aggregate"]["net_return"]["mean"] < 0
    assert all(v < 3 for v in expected.values())


def test_the_p3_comparison_reports_a_negative_result():
    """P3's frozen verdict. Same reasoning as the P2b and P2c pins above.

    Not a test of the machinery — a test of the *finding*. P3 answered no, and
    the six fold counts below are what that means. If a later change to the
    comparison moves any of them, the result changed, and that has to be a
    deliberate act with its own evidence rather than a diff nobody read.
    """
    payload = _comparison("btc_p3_comparison")
    assert payload["sealed_test"] is False
    assert payload["independent_recompute"]["mismatches"] == 0
    assert payload["snapshot_anchoring"]["problems"] == 0

    expected = {
        ("logistic_regression", "microstructure_v1"): 1,
        ("logistic_regression", "ohlcv14_plus_microstructure_v1"): 2,
        ("lightgbm", "microstructure_v1"): 1,
        ("lightgbm", "ohlcv14_plus_microstructure_v1"): 2,
        ("xgboost", "microstructure_v1"): 2,
        ("xgboost", "ohlcv14_plus_microstructure_v1"): 1,
    }
    for (model, arm), folds in expected.items():
        assert payload["deltas"][model][arm]["net_return_improved_folds"] == folds

    # The predeclared bar is three of four. Nothing reached it, which is the
    # finding; asserting it here stops "P3 was positive" from ever being true
    # of this directory without someone changing this line.
    assert all(v < 3 for v in expected.values())


def test_the_committed_predictions_are_the_bytes_the_manifests_pin():
    """A cell's parquet is primary evidence and is covered, not merely present."""
    covered = {
        name
        for manifest in (
            "btc_p2b_SHA256SUMS.txt",
            "btc_p2c_SHA256SUMS.txt",
            "btc_p3_SHA256SUMS.txt",
        )
        for _, name in freeze_evidence.manifest_entries(ROOT / "artifacts" / manifest)
    }
    for prefix, arms in (
        ("btc_p2b", ("ohlcv14", "smc_v1", "ohlcv14_plus_smc_v1")),
        (
            "btc_p2c",
            ("ohlcv14", "chart_structure_v1", "ohlcv14_plus_chart_structure_v1"),
        ),
        (
            "btc_p3",
            ("ohlcv14", "microstructure_v1", "ohlcv14_plus_microstructure_v1"),
        ),
    ):
        for arm in arms:
            for model in ("logistic_regression", "lightgbm", "xgboost"):
                relative = (
                    f"artifacts/benchmark/{prefix}_{arm}_{model}/outer_predictions.parquet"
                )
                assert relative in covered, relative
                assert (ROOT / relative).is_file()


def test_a_manifest_entry_is_a_sha256_of_the_file_it_names():
    """Independent of `check`: re-derive one digest by hand.

    `check` could be wrong in the same direction as `freeze` and both tests
    above would still pass. This one hashes a file directly.
    """
    manifest = ROOT / "artifacts" / "btc_p2b_SHA256SUMS.txt"
    expected, name = freeze_evidence.manifest_entries(manifest)[0]
    assert hashlib.sha256((ROOT / name).read_bytes()).hexdigest() == expected


# --------------------------------------------------------------------------- #
# D. the documentation says what the history supports
#
# The last item on the adversarial list, and the only one a checksum cannot
# reach: a specification claiming more independence than git gives it. These
# assert wording, which is unusual and deliberate — `chart_structure_v1.md`
# opened with `smc_v1`'s checkpoint and `smc_v1`'s question for the length of
# two checkpoints, and no test in this repository could have noticed.
# --------------------------------------------------------------------------- #
DOCS = ROOT / "docs"


FEATURE_SPECS = (
    ("smc_v1.md", "P2b", "smc_v1"),
    ("chart_structure_v1.md", "P2c", "chart_structure_v1"),
    ("microstructure_v1.md", "P3", "microstructure_v1"),
    ("derivatives_v1.md", "P4", "derivatives_v1"),
    ("mtf_v1.md", "P5", "mtf_v1"),
)


@pytest.mark.parametrize("document, checkpoint, family", FEATURE_SPECS)
def test_each_feature_spec_names_its_own_checkpoint(document, checkpoint, family):
    """Every spec uses the same header line, and it has to name the right one.

    `chart_structure_v1.md` carried `Research checkpoint: **P2b**` — `smc_v1`'s
    checkpoint, with `smc_v1`'s question — through two checkpoints.
    """
    text = (DOCS / document).read_text()
    _, _, rest = text.partition("Research checkpoint:")
    assert rest, f"{document} no longer states a research checkpoint"
    assert rest.lstrip().startswith(f"**{checkpoint}**"), rest[:80]
    for other, *_ in ((c,) for _, c, _ in FEATURE_SPECS):
        if other != checkpoint:
            assert f"Research checkpoint: **{other}**" not in text
    # The question beside the header must be about this document's own family.
    assert family in rest[:400], rest[:400]


def test_every_declared_information_family_has_a_committed_spec():
    """A family that ran without a predeclaration is the failure this prevents."""
    families = {family for _, _, family in FEATURE_SPECS}
    for name, checkpoint in CHECKPOINTS.items():
        assert checkpoint.family in families, f"{name} measures an undocumented family"


def test_the_chart_spec_states_its_adaptive_status_rather_than_implying_none():
    chart = (DOCS / "chart_structure_v1.md").read_text()
    assert "Status: adaptive research evidence" in chart
    assert "Not a pristine out-of-sample confirmation" in chart
    # The claim it is allowed to make, and the one it is not.
    assert "before any P2b outer-validation number existed" in chart
    assert "predeclared before any P2b outer-validation result was observed" not in chart


def test_no_document_calls_a_frozen_hash_stale_by_design():
    """The phrase that meant "this checksum is allowed to be wrong"."""
    for path in [ROOT / "artifacts" / "README.md", *DOCS.glob("*.md"), ROOT / "README.md"]:
        assert "stale by design" not in path.read_text(), path


def test_no_document_claims_ohlcv_alpha_has_been_disproved():
    """The overstatement two negative checkpoints invite.

    The evidence is against spending the next checkpoint on another
    hand-designed transformation of the same hourly bars. It is not a proof
    about a space of possible features.
    """
    forbidden = (
        "OHLCV information is proven exhausted",
        "there is no OHLCV alpha",
        "five hourly values contain no predictive information",
        "proven exhausted",
    )
    for path in [ROOT / "README.md", ROOT / "artifacts" / "README.md", *DOCS.glob("*.md")]:
        text = path.read_text()
        for phrase in forbidden:
            assert phrase not in text, f"{path.name}: {phrase!r}"


def test_the_repository_has_the_manifests_these_tests_think_it_has():
    """Discovery is convenient and silent; a deleted manifest would just vanish.

    Globbing means a new checkpoint is covered automatically. It also means a
    manifest that disappeared would take its own verification with it and no
    test above would fail, so the set is named once, here.
    """
    assert MANIFESTS == (
        "btc_p13_SHA256SUMS.txt",
        # P13-A2R2's source acquisition: 260 published Binance objects, each
        # checksum-verified, described but not committed. A separate manifest from
        # btc_p13_SHA256SUMS.txt because it covers a separate directory generated
        # under a different design, and the earlier one is frozen.
        "btc_p13_a2r2_source_acquisition_SHA256SUMS.txt",
        "btc_p2a_SHA256SUMS.txt",
        "btc_p2b_SHA256SUMS.txt",
        "btc_p2b_ablation_SHA256SUMS.txt",
        "btc_p2c_SHA256SUMS.txt",
        "btc_p3_SHA256SUMS.txt",
        "btc_p4_screen_SHA256SUMS.txt",
        "btc_p4_stage1_SHA256SUMS.txt",
        "btc_p5_SHA256SUMS.txt",
        "btc_p5_decision_SHA256SUMS.txt",
        "btc_p6_SHA256SUMS.txt",
        "btc_p6_decision_SHA256SUMS.txt",
        "btc_p6ext_SHA256SUMS.txt",
        "btc_p6ext_decision_SHA256SUMS.txt",
        "btc_p7_SHA256SUMS.txt",
        "btc_p7_decision_SHA256SUMS.txt",
        "btc_v4_SHA256SUMS.txt",
    )


def test_no_manifest_was_left_behind_under_another_name():
    """The four branch-only manifests were re-cut, not archived beside the new ones.

    A `*.superseded.txt` next to a live manifest is a checksum file nobody
    expects to verify, which is the habit this branch exists to break. These
    four never reached `main`, so re-cutting them rewrites no history and there
    is nothing to keep a copy of.
    """
    stragglers = sorted(p.name for p in (ROOT / "artifacts").glob("*SHA256SUMS*"))
    assert stragglers == sorted(MANIFESTS), stragglers


# --------------------------------------------------------------------------- #
# E. the derived reports nothing was checking
#
# The two comparisons are pinned by their fold counts, verdicts and integrity
# counters. The ablation table and the regime description had neither a hash nor
# an assertion: they are derived, so freezing them is wrong, and nothing else
# looked at them at all. Both carry research-relevant numbers — the six family
# contributions, the per-fold deltas behind the regime reading — and both are
# regenerated by a tool that could start producing different ones without a
# single test noticing.
#
# They are checked the way a derived report should be: **recomputed from the
# primary evidence behind them**. Each helper below is a pure function of
# (payload, cells) so the real evidence exercises it and a tampered payload can
# falsify it without copying the committed artifacts.
# --------------------------------------------------------------------------- #
def _fold_net_returns(cell: str, model: str) -> dict[int, float]:
    """One cell's outer net return per fold, read from the cell itself."""
    payload = json.loads((BENCHMARK / cell / "p2b.json").read_text())
    return {
        int(record["fold"]): record["outer_validation"][model]["trading"]["net_return"]
        for record in payload["folds"]
    }


def ablation_mismatches(payload: dict, net_returns) -> list[str]:
    """Every ablation number that is not what the cells behind it imply.

    ``net_returns(cell_directory)`` returns ``{fold: net_return}``. The delta
    definition is the artifact's own: full minus ablated, per fold, on identical
    rows.
    """
    problems: list[str] = []
    model = payload["model"]
    full = net_returns(f"btc_p2b_{payload['reference_arm']}_{model}")
    for family, block in payload["families"].items():
        ablated = net_returns(f"btc_p2b_{block['arm']}_{model}")
        for record in block["per_fold"]:
            fold = int(record["fold"])
            for key, expected in (
                ("full_net_return", full[fold]),
                ("ablated_net_return", ablated[fold]),
                ("net_return", round(full[fold] - ablated[fold], 6)),
            ):
                if record[key] != round(expected, 6):
                    problems.append(
                        f"{family} fold {fold} {key}: report says {record[key]}, the "
                        f"cells give {round(expected, 6)}"
                    )
        deltas = [record["net_return"] for record in block["per_fold"]]
        mean = round(sum(deltas) / len(deltas), 6)
        if block["aggregate"]["net_return"]["mean"] != mean:
            problems.append(
                f"{family} mean delta: report says "
                f"{block['aggregate']['net_return']['mean']}, its own folds give {mean}"
            )
        signs = block["sign_consistency"]["net_return"]
        if signs["positive"] != sum(1 for d in deltas if d > 0):
            problems.append(f"{family} positive-fold count disagrees with its own deltas")
        if signs["negative"] != sum(1 for d in deltas if d < 0):
            problems.append(f"{family} negative-fold count disagrees with its own deltas")
    return problems


def regime_delta_mismatches(payload: dict, net_returns) -> list[str]:
    """Every per-fold delta in the regime description the cells do not support."""
    problems: list[str] = []
    for model, by_fold in payload["deltas_by_model"].items():
        control = net_returns(f"btc_p2b_ohlcv14_{model}")
        for fold, arms in by_fold.items():
            for arm, delta in arms.items():
                theirs = net_returns(f"btc_p2b_{arm}_{model}")
                expected = round(theirs[int(fold)] - control[int(fold)], 6)
                if delta != expected:
                    problems.append(
                        f"{model} fold {fold} {arm}: report says {delta}, the cells "
                        f"give {expected}"
                    )
    return problems


def test_the_ablation_table_is_recomputed_from_the_cells_behind_it():
    payload = json.loads(
        (BENCHMARK / "btc_p2b_ablation_xgboost" / "p2b_ablation.json").read_text()
    )
    assert payload["evidence_class"] == DERIVED
    assert ablation_mismatches(payload, lambda c: _fold_net_returns(c, payload["model"])) == []


@pytest.mark.parametrize("model", ["logistic_regression", "lightgbm", "xgboost"])
def test_the_regime_description_is_recomputed_from_the_cells_behind_it(model):
    """One model at a time, because a cell's net return is per model.

    `net_returns` is closed over the model under test rather than parsed back
    out of a directory name, which would be a second place to get it wrong.
    """
    payload = json.loads((BENCHMARK / "btc_p2b_regimes" / "p2b_regimes.json").read_text())
    assert payload["evidence_class"] == DERIVED
    assert payload["sealed_test"] is False
    one_model = {**payload, "deltas_by_model": {model: payload["deltas_by_model"][model]}}
    assert (
        regime_delta_mismatches(one_model, lambda cell: _fold_net_returns(cell, model)) == []
    )


def test_the_ablation_finding_is_that_no_family_carries_the_arm():
    """The headline, pinned. A family that started carrying the combined arm
    would be a change of finding, and has to be a deliberate act."""
    payload = json.loads(
        (BENCHMARK / "btc_p2b_ablation_xgboost" / "p2b_ablation.json").read_text()
    )
    carried = [
        family
        for family, block in payload["families"].items()
        if block["aggregate"]["net_return"]["mean"] > 0
        and block["sign_consistency"]["net_return"]["agreeing_folds"] == 4
    ]
    assert carried == [], f"{carried} now shows a consistent positive contribution"
    # The families that do agree in 3 or 4 folds agree on the negative direction:
    # removing them helped more often than not.
    for family, block in payload["families"].items():
        signs = block["sign_consistency"]["net_return"]
        if signs["agreeing_folds"] >= 3:
            assert signs["direction"] == "negative", f"{family} is {signs['direction']}"


def test_the_four_outer_periods_are_the_ones_the_write_up_describes():
    """`artifacts/README.md` and the roadmap both describe these four blocks as
    positive-return, low-directionality stretches. If that stopped being true the
    prose would be wrong and nothing else would say so."""
    payload = json.loads((BENCHMARK / "btc_p2b_regimes" / "p2b_regimes.json").read_text())
    assert [p["fold"] for p in payload["periods"]] == [0, 1, 2, 3]
    ratios = []
    for period in payload["periods"]:
        market = period["market"]
        assert market["total_return"] > 0, f"fold {period['fold']} was not positive-return"
        ratios.append(round(market["directionality"], 4))
    # The band the roadmap quotes, taken from the artifact rather than from
    # memory. It said 0.012-0.055 until this test was written, which is fold 0's
    # ratio mistaken for the minimum — fold 2 is 0.0030, an order of magnitude
    # lower and the choppiest of the four. The artifact's own `observations`
    # said so all along; the prose had simply never been checked against it.
    assert min(ratios) == 0.0030 and max(ratios) == 0.0552, ratios
    assert all(r < 0.06 for r in ratios), "these are low-directionality blocks"


# --- and the same two checks, falsified ---------------------------------------
#
# A recomputation that cannot fail is decoration. Both helpers are pure
# functions of (payload, cells), so a tampered payload can be fed to them
# without touching a committed artifact.
def _ablation_payload() -> dict:
    return json.loads(
        (BENCHMARK / "btc_p2b_ablation_xgboost" / "p2b_ablation.json").read_text()
    )


def _regimes_payload() -> dict:
    return json.loads((BENCHMARK / "btc_p2b_regimes" / "p2b_regimes.json").read_text())


def test_an_ablation_delta_edited_away_from_its_cells_is_reported():
    payload = _ablation_payload()
    payload["families"]["structure"]["per_fold"][1]["net_return"] += 0.05
    problems = ablation_mismatches(payload, lambda c: _fold_net_returns(c, payload["model"]))
    assert any("structure fold 1 net_return" in p for p in problems), problems


def test_an_ablation_mean_edited_away_from_its_own_folds_is_reported():
    """The mean is a function of the four deltas beside it, so a report can
    disagree with itself without any cell being touched."""
    payload = _ablation_payload()
    payload["families"]["fvg"]["aggregate"]["net_return"]["mean"] = 0.5
    problems = ablation_mismatches(payload, lambda c: _fold_net_returns(c, payload["model"]))
    assert any("fvg mean delta" in p for p in problems), problems


def test_an_ablation_sign_count_edited_away_from_its_own_deltas_is_reported():
    payload = _ablation_payload()
    payload["families"]["sweeps"]["sign_consistency"]["net_return"]["positive"] = 4
    problems = ablation_mismatches(payload, lambda c: _fold_net_returns(c, payload["model"]))
    assert any("sweeps positive-fold count" in p for p in problems), problems


def test_a_regime_delta_edited_away_from_its_cells_is_reported():
    payload = _regimes_payload()
    payload["deltas_by_model"]["xgboost"]["2"]["smc_v1"] += 0.2
    one_model = {
        **payload,
        "deltas_by_model": {"xgboost": payload["deltas_by_model"]["xgboost"]},
    }
    problems = regime_delta_mismatches(
        one_model, lambda cell: _fold_net_returns(cell, "xgboost")
    )
    assert any("xgboost fold 2 smc_v1" in p for p in problems), problems


def test_a_regime_delta_attributed_to_the_wrong_arm_is_reported():
    """Right numbers, wrong labels: the two arms' deltas exchanged."""
    payload = _regimes_payload()
    block = payload["deltas_by_model"]["lightgbm"]["0"]
    block["smc_v1"], block["ohlcv14_plus_smc_v1"] = (
        block["ohlcv14_plus_smc_v1"],
        block["smc_v1"],
    )
    one_model = {
        **payload,
        "deltas_by_model": {"lightgbm": payload["deltas_by_model"]["lightgbm"]},
    }
    problems = regime_delta_mismatches(
        one_model, lambda cell: _fold_net_returns(cell, "lightgbm")
    )
    assert len(problems) == 2, problems


# --------------------------------------------------------------------------- #
# F. coverage cannot be opted out of by the thing being covered
#
# `evidence_class` lives in the artifact's own JSON, and the freeze tool reads
# it to decide what to hash. That is the right default — a new aggregator has to
# opt *into* being excluded rather than remember to opt out — but it also means
# the file decides whether it is covered. A cell that flipped itself to
# "derived" would be dropped by the next freeze, and every test above would
# still pass: the manifest would cover only declared-primary directories, no
# covered directory would be derived, and the cell would simply have vanished
# from the evidence.
#
# So what is expected to be primary is declared **here**, out of reach of
# anything under `artifacts/`, and derived from the checkpoint definitions in
# `nn.information_sets` rather than from a directory listing. A checkpoint that
# gains an arm gains a required cell, and no artifact can edit this list.
# --------------------------------------------------------------------------- #
CELL_MANIFEST = {
    "P2b": "btc_p2b_SHA256SUMS.txt",
    "P2c": "btc_p2c_SHA256SUMS.txt",
    "P3": "btc_p3_SHA256SUMS.txt",
    "P4": "btc_p4_stage1_SHA256SUMS.txt",
    "P5": "btc_p5_SHA256SUMS.txt",
}
ABLATION_MANIFEST = "btc_p2b_ablation_SHA256SUMS.txt"

#: Checkpoints this repository declares but has produced **no evidence for**,
#: and the manifest each one will be frozen under when it does.
#:
#: Declared rather than inferred, and for the same reason the rest of this
#: section exists. A checkpoint with no cells is invisible to a coverage check
#: built from directory listings: nothing is missing because nothing is
#: expected. Naming it here means the repository has to say *why* a declared
#: checkpoint has no evidence, and
#: `test_an_unrun_checkpoint_has_no_evidence_directories` fails the moment one
#: appears without being moved into `CELL_MANIFEST`.
UNRUN_CHECKPOINTS: dict[str, str] = {}


def expected_primary() -> dict[str, str]:
    """Directory name -> the manifest that must cover it, in full."""
    expected: dict[str, str] = {}
    for checkpoint, manifest in CELL_MANIFEST.items():
        for arm in CHECKPOINTS[checkpoint].arms:
            for model in SIMPLE_MODEL_NAMES:
                expected[f"btc_{checkpoint.lower()}_{arm}_{model}"] = manifest
    for arm in ablation_set_names():
        expected[f"btc_p2b_{arm}_xgboost"] = ABLATION_MANIFEST
    expected["btc_p2b_repro_ohlcv14_plus_smc_v1_xgboost"] = ABLATION_MANIFEST
    return expected


def coverage(entries_by_manifest: dict[str, list[str]]) -> dict[str, set[str]]:
    """Directory name -> the manifests covering any file in it."""
    covered: dict[str, set[str]] = {}
    for manifest, names in entries_by_manifest.items():
        for name in names:
            covered.setdefault(Path(name).parent.name, set()).add(manifest)
    return covered


def coverage_problems(
    expected: dict[str, str], entries_by_manifest: dict[str, list[str]]
) -> list[str]:
    """Every expected primary directory not covered exactly once, by the right manifest."""
    covered = coverage(entries_by_manifest)
    problems: list[str] = []
    for directory, manifest in sorted(expected.items()):
        found = covered.get(directory, set())
        if not found:
            problems.append(
                f"{directory} is expected primary evidence and no manifest covers it"
            )
        elif len(found) > 1:
            problems.append(f"{directory} is covered by {sorted(found)}; exactly one may")
        elif found != {manifest}:
            problems.append(f"{directory} is covered by {found.pop()}, expected {manifest}")
    return problems


def _committed_entries() -> dict[str, list[str]]:
    return {
        manifest: [
            name for _, name in freeze_evidence.manifest_entries(ROOT / "artifacts" / manifest)
        ]
        for manifest in MANIFESTS
    }


def test_every_declared_checkpoint_is_frozen_or_declared_unrun():
    """No checkpoint may be neither. That is how one would escape coverage."""
    assert set(CHECKPOINTS) == set(CELL_MANIFEST) | set(UNRUN_CHECKPOINTS)
    assert not set(CELL_MANIFEST) & set(UNRUN_CHECKPOINTS)


@pytest.mark.parametrize("checkpoint", sorted(UNRUN_CHECKPOINTS))
def test_an_unrun_checkpoint_has_no_evidence_directories(checkpoint):
    """A checkpoint declared unrun must have produced nothing at all.

    The moment a cell appears, this fails — and the fix is to move the
    checkpoint into `CELL_MANIFEST`, which immediately demands all nine cells,
    their manifest, and every file inside each directory. Evidence cannot
    arrive quietly.
    """
    prefix = f"btc_{checkpoint.lower()}_"
    strays = sorted(p.name for p in BENCHMARK.glob(f"{prefix}*"))
    assert strays == [], (
        f"{checkpoint} is declared unrun but {strays} exist. Move it into "
        "CELL_MANIFEST and freeze its cells rather than leaving them uncovered."
    )
    assert not (ROOT / "artifacts" / UNRUN_CHECKPOINTS[checkpoint]).exists()


def test_every_expected_primary_directory_is_covered_exactly_once():
    assert coverage_problems(expected_primary(), _committed_entries()) == []


def test_every_file_in_an_expected_primary_directory_is_covered():
    """Coverage of a directory is not coverage of the cell.

    A manifest naming `p2b.json` and not `outer_predictions.parquet` would pass
    the check above while leaving the per-sample evidence unpinned.
    """
    entries = _committed_entries()
    covered = {name for names in entries.values() for name in names}
    for directory in expected_primary():
        on_disk = {
            f"artifacts/benchmark/{directory}/{p.name}"
            for p in (BENCHMARK / directory).iterdir()
            if p.suffix in freeze_evidence.EVIDENCE_SUFFIXES
        }
        assert on_disk, f"{directory} holds no evidence files"
        assert on_disk <= covered, f"{directory}: uncovered {sorted(on_disk - covered)}"


def test_no_expected_primary_directory_declares_itself_derived():
    """The opt-out this section exists to close, stated as its own failure.

    Without this, a cell that flipped to "derived" would fail
    `test_no_manifest_covers_derived_evidence` instead — which reads as "remove
    it from the manifest" when the correct answer is "a cell is not derived".
    """
    for directory in expected_primary():
        declared = freeze_evidence.evidence_class_of(BENCHMARK / directory)
        assert declared == PRIMARY, f"{directory} declares {declared!r}"


# --- and falsified ------------------------------------------------------------
#
# Against a synthetic manifest set rather than the committed one, deliberately:
# a check on coverage must be falsifiable without the evidence it guards being
# in place, or it cannot be trusted at the moment the coverage is being cut.
def _synthetic_entries(expected: dict[str, str]) -> dict[str, list[str]]:
    """Exactly the coverage `expected` asks for: two files per directory."""
    entries: dict[str, list[str]] = {manifest: [] for manifest in set(expected.values())}
    for directory, manifest in expected.items():
        entries[manifest] += [
            f"artifacts/benchmark/{directory}/p2b.json",
            f"artifacts/benchmark/{directory}/outer_predictions.parquet",
        ]
    return entries


def test_complete_coverage_reports_nothing():
    """The control. A checker that always complained would pass the three below."""
    expected = expected_primary()
    assert coverage_problems(expected, _synthetic_entries(expected)) == []


def test_a_cell_that_removed_itself_from_coverage_is_reported():
    """The attack this section exists for: a cell relabels itself `derived`, so
    the next freeze drops it, and the manifests stay internally consistent."""
    expected = expected_primary()
    entries = _synthetic_entries(expected)
    victim = "btc_p2c_chart_structure_v1_xgboost"
    entries[CELL_MANIFEST["P2c"]] = [
        n for n in entries[CELL_MANIFEST["P2c"]] if f"/{victim}/" not in n
    ]
    assert coverage_problems(expected, entries) == [
        f"{victim} is expected primary evidence and no manifest covers it"
    ]


def test_a_cell_covered_by_two_manifests_is_reported():
    expected = expected_primary()
    entries = _synthetic_entries(expected)
    entries[ABLATION_MANIFEST] += ["artifacts/benchmark/btc_p2b_ohlcv14_xgboost/p2b.json"]
    both = sorted([ABLATION_MANIFEST, CELL_MANIFEST["P2b"]])
    assert coverage_problems(expected, entries) == [
        f"btc_p2b_ohlcv14_xgboost is covered by {both}; exactly one may"
    ]


def test_a_cell_covered_by_the_wrong_manifest_is_reported():
    expected = expected_primary()
    entries = _synthetic_entries(expected)
    moved = [n for n in entries[CELL_MANIFEST["P2b"]] if "/btc_p2b_smc_v1_lightgbm/" in n]
    entries[CELL_MANIFEST["P2b"]] = [
        n for n in entries[CELL_MANIFEST["P2b"]] if n not in moved
    ]
    entries[ABLATION_MANIFEST] += moved
    assert coverage_problems(expected, entries) == [
        f"btc_p2b_smc_v1_lightgbm is covered by {ABLATION_MANIFEST}, "
        f"expected {CELL_MANIFEST['P2b']}"
    ]


def test_the_inventory_grows_with_the_checkpoint_definitions():
    """It is derived from `nn.information_sets`, not from a directory listing.

    Nine cells per checkpoint, five checkpoints, plus six ablation arms and
    the determinism re-run. If a checkpoint gained an arm this would require
    a cell for it, which is the point of deriving it from the declaration
    rather than from what exists.
    """
    expected = expected_primary()
    assert len(expected) == 9 * 5 + 6 + 1
    assert sum(1 for m in expected.values() if m == "btc_p2b_SHA256SUMS.txt") == 9
    assert sum(1 for m in expected.values() if m == "btc_p2c_SHA256SUMS.txt") == 9
    assert sum(1 for m in expected.values() if m == "btc_p3_SHA256SUMS.txt") == 9
    assert sum(1 for m in expected.values() if m == ABLATION_MANIFEST) == 7
    assert "btc_p2c_chart_structure_v1_xgboost" in expected
    assert "btc_p2b_ohlcv14_plus_smc_v1_minus_fvg_xgboost" in expected
    assert "btc_p3_microstructure_v1_xgboost" in expected
