"""Synthetic normalized days, for tests and drills only.

Section 12.3 line 1444: "synthetic normalized-day generator for tests (no
market data)". Section 10 sizes the acceptance run at "48 hours of synthetic
normalized files generated by `chimera/demo/fixtures.py` (not real market data;
no economic meaning), with fault schedules".

**Every number this module produces is invented by a deterministic formula from
a seed.** Nothing here reads a market, a recorded file, or a clock. The prices
are a fixed sawtooth around a constant, chosen so a carry rule has something to
size against and nothing else; they are not a simulation of anything, and no
economic conclusion may be drawn from a run over them. That is the point: the
acceptance criterion for the demo runner is that the machinery behaves, not
that it earns.

The schema is not restated here. A generated frame is validated by handing it
to :func:`chimera.recorder.normalize.digest`, which refuses a frame whose
columns are not exactly the recorder's, so a fixture cannot drift away from the
format the runner will meet in production.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import pandas as pd

from chimera.recorder.contract import RecorderContract
from chimera.recorder.normalize import (
    NORMALIZED_SCHEMA,
    MinuteNormalizer,
    columns_for,
    digest,
)

__all__ = ["SyntheticFeed", "MinuteShape", "DAY_MS", "MINUTE_MS"]

MINUTE_MS = 60_000
DAY_MS = 24 * 60 * MINUTE_MS
_MINUTES_PER_DAY = 1440


@dataclass(frozen=True)
class MinuteShape:
    """What a single generated minute should look like.

    Absence is expressible on purpose: a minute that is not present at all, or
    one present without a book or without a mark, is how a fixture exercises
    section 2.2's `complete == False` path without corrupting a file.
    """

    present: bool = True
    book: bool = True
    mark: bool = True


class SyntheticFeed:
    """Writes synthetic normalized days under a storage root.

    The layout is the recorder's, taken from `MinuteNormalizer` rather than
    rebuilt, so a fixture and a real day are indistinguishable to `FeedCursor`.
    """

    def __init__(
        self,
        root: str | Path,
        contract: RecorderContract,
        *,
        seed: int = 7,
        spot_base: float = 30000.0,
        basis: float = 30.0,
    ) -> None:
        self.root = Path(root)
        self.contract = contract
        self.normalizer = MinuteNormalizer(self.root, contract)
        self.seed = int(seed)
        self.spot_base = float(spot_base)
        self.basis = float(basis)

    # --- the invented price path ------------------------------------------
    def spot_close(self, minute_index: int) -> float:
        """A sawtooth around ``spot_base``. Deterministic in the seed and index.

        Deliberately not a random walk: a fixture whose path depends on a global
        RNG makes a failing acceptance run hard to reproduce, and there is no
        economic claim here that a more realistic path would improve.
        """
        span = 200.0
        period = 240
        offset = (minute_index + self.seed * 17) % period
        leg = offset / period
        wave = leg * 2.0 if leg < 0.5 else (1.0 - leg) * 2.0
        return round(self.spot_base + (wave - 0.5) * span, 2)

    def perp_close(self, minute_index: int) -> float:
        return round(self.spot_close(minute_index) + self.basis, 2)

    # --- frames -----------------------------------------------------------
    def _row(self, market: str, minute_open_ms: int, index: int, shape: MinuteShape) -> dict:
        close = self.perp_close(index) if market == "um" else self.spot_close(index)
        row: dict[str, Any] = {
            "minute_open_ms": minute_open_ms,
            "kline_close_ms": minute_open_ms + MINUTE_MS - 1,
            "kline_source": "synthetic",
            "kline_open": close,
            "kline_high": round(close + 1.0, 2),
            "kline_low": round(close - 1.0, 2),
            "kline_close": close,
            "kline_volume": 1.0,
            "kline_trades": 10,
            "kline_taker_buy_base": 0.5,
            "kline_taker_buy_quote": round(close * 0.5, 2),
        }
        if market == "um":
            mark = round(close, 2) if shape.mark else None
            row.update(
                {
                    "mark_present": bool(shape.mark),
                    "mark_open": mark,
                    "mark_high": mark,
                    "mark_low": mark,
                    "mark_close": mark,
                    "index_open": mark,
                    "index_high": mark,
                    "index_low": mark,
                    "index_close": mark,
                    "mark_events": 1 if shape.mark else 0,
                    "funding_rate_last": 0.0001 if shape.mark else None,
                    "next_funding_time_ms": self._next_funding_ms(minute_open_ms),
                }
            )
        if shape.book:
            row.update(
                {
                    "book_present": True,
                    "book_bid": round(close - 0.5, 2),
                    "book_bid_qty": 50.0,
                    "book_ask": round(close + 0.5, 2),
                    "book_ask_qty": 50.0,
                    "book_update_id": 1_000_000 + index,
                    "book_canonical_ms": minute_open_ms + MINUTE_MS - 1,
                    "book_time_basis": "event",
                }
            )
        else:
            row.update(
                {
                    "book_present": False,
                    "book_bid": None,
                    "book_bid_qty": None,
                    "book_ask": None,
                    "book_ask_qty": None,
                    "book_update_id": None,
                    "book_canonical_ms": None,
                    "book_time_basis": None,
                }
            )
        return row

    @staticmethod
    def _next_funding_ms(minute_open_ms: int) -> int:
        """The next 8-hourly boundary strictly after this minute."""
        eight_hours = 8 * 60 * 60 * 1000
        return ((minute_open_ms // eight_hours) + 1) * eight_hours

    def frame(
        self, market: str, day: str, shapes: Mapping[int, MinuteShape] | None = None
    ) -> pd.DataFrame:
        """One day of one market as the recorder would have stored it."""
        shapes = dict(shapes or {})
        start_ms = int(pd.Timestamp(day, tz="UTC").timestamp() * 1000)
        rows = []
        for slot in range(_MINUTES_PER_DAY):
            shape = shapes.get(slot, MinuteShape())
            if not shape.present:
                continue  # a minute with no captured kline has no row at all
            rows.append(self._row(market, start_ms + slot * MINUTE_MS, slot, shape))

        specs = columns_for(market)
        frame = pd.DataFrame(rows, columns=[s.name for s in specs])
        for spec in specs:
            frame[spec.name] = frame[spec.name].astype(spec.dtype)
        # Refuses anything that is not exactly the recorder's schema.
        digest(frame, market=market)
        return frame

    # --- writing ----------------------------------------------------------
    def write_day(
        self, market: str, day: str, shapes: Mapping[int, MinuteShape] | None = None
    ) -> Path:
        frame = self.frame(market, day, shapes)
        parquet = self.normalizer.parquet_path(market, day)
        parquet.parent.mkdir(parents=True, exist_ok=True)
        frame.to_parquet(parquet, index=False)
        meta = {
            "schema": NORMALIZED_SCHEMA,
            "market": market,
            "day": day,
            "rows": int(len(frame)),
            "digest": digest(frame, market=market),
            "synthetic": True,
            "note": "generated by chimera.demo.fixtures; not market data",
        }
        self.normalizer.meta_path(market, day).write_text(
            json.dumps(meta, sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8"
        )
        return parquet

    def write_days(
        self,
        days: Sequence[str],
        *,
        shapes: Mapping[str, Mapping[int, MinuteShape]] | None = None,
        markets: Iterable[str] = ("um", "spot"),
    ) -> None:
        shapes = dict(shapes or {})
        for day in days:
            for market in markets:
                self.write_day(market, day, shapes.get(f"{market}:{day}"))

    def write_settlements(
        self,
        days: Sequence[str],
        *,
        rate: str = "0.0001",
        rates: Mapping[tuple[str, int], str] | None = None,
        mark_price: str | None = None,
        duplicate: Sequence[tuple[str, int]] = (),
        hours: Sequence[int] = (0, 8, 16),
    ) -> Path:
        """Eight-hourly settlements across the given days.

        The row shape is the recorder's own, from
        :meth:`chimera.recorder.events.FundingSettlement.to_settlement_record`,
        and not an invention of this module. Before PR-10R it was an invention --
        the instant was written as ``settlement_ms`` and there was no
        ``mark_price`` at all -- which made the fixture and a real recorded day
        distinguishable to :class:`~chimera.demo.feed.FeedCursor` in exactly the
        place the funding path reads, and hid a live defect in it.

        ``rates`` overrides the rate for one ``(day, hour)`` so a drill can put a
        pay and a receive settlement in the same run; ``duplicate`` writes a
        second, byte-identical row for one ``(day, hour)`` so the exactly-once
        gate has something to refuse. Neither is reachable from a campaign
        configuration: this module is imported by tests and drills only.
        """
        path = self.normalizer.settlements_path("um")
        path.parent.mkdir(parents=True, exist_ok=True)
        overrides = dict(rates or {})
        repeated = set(duplicate)
        lines = []
        for day in days:
            start = int(pd.Timestamp(day, tz="UTC").timestamp() * 1000)
            for hour in hours:
                at = start + hour * 60 * 60 * 1000
                minute_index = hour * 60
                row = {
                    "funding_time_ms": at,
                    "funding_time_utc": pd.Timestamp(at, unit="ms", tz="UTC").isoformat(),
                    "funding_rate": overrides.get((day, hour), rate),
                    # The settlement's own mark, as the venue published it. The
                    # generated mark series is what a recorded day would carry at
                    # that instant, so the fixture stays one deterministic price
                    # path rather than two.
                    "mark_price": mark_price or f"{self.perp_close(minute_index):.2f}",
                    "rate_type": None,
                    "symbol": "BTCUSDT",
                    "receipt_wall_ns": at * 1_000_000,
                }
                line = json.dumps(row, sort_keys=True, separators=(",", ":"))
                lines.append(line)
                if (day, hour) in repeated:
                    lines.append(line)
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return path
