name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install deps
        run: pip install -r nn/requirements.txt
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push bot image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bot:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push nn_infer
        uses: docker/build-push-action@v5
        with:
          context: nn
          file: nn/Dockerfile.nn_infer
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nn_infer:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/nn_infer:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
