name: Nightly Train & Deploy

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  train:
    runs-on: self-hosted-gpu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r nn/requirements.txt
      - name: Train model
        run: python nn/train.py --features data/features/binance_BTC_USDT_1h_2020-01-01_features.parquet --epochs 20
      - name: Check model version & deploy
        run: |
          if mlflow models list | grep -q 'nn_predictor'; then
            docker buildx build --push \
              --file nn/Dockerfile.nn_infer \
              --tag ghcr.io/<org>/nn_infer:latest \
              --cache-from=type=gha --cache-to=type=gha,mode=max .
          fi
