name: Train

on:
  push:
    paths:
      - 'nn/**'
  schedule:
    - cron: '0 2 * * *'

jobs:
  train:
    runs-on: [self-hosted, gpu]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('nn/requirements.txt') }}
      - name: Install deps
        run: pip install -r nn/requirements.txt
      - name: Train
        run: python nn/train.py
      - name: Update MLflow alias
        run: |
          python - <<'PY'
import mlflow
client = mlflow.tracking.MlflowClient()
model = client.get_latest_versions("nn_predictor", stages=[])[-1]
client.set_registered_model_alias("nn_predictor", "prod", model.version)
PY

